### ISSUE TITLE
Segmentation fault parsing `let %`

### ISSUE THREAD

**Issue by the-mikedavis** [nickel-lang/tree-sitter-nickel#10]
Hello! 👋

It looks like there's an edge case that causes the parser to segfault:

```
$ echo "let %" > test.ncl
$ tree-sitter parse test.ncl
Segmentation fault (core dumped)
```

I'm not sure where it's coming from - mostly I've seen segfaults come from bugs in external scanners but I've also seen one come from the parser without an external scanner (https://github.com/victorhqc/tree-sitter-prisma/pull/39). 

Originally reported in https://github.com/helix-editor/helix/issues/2979

**Comment by ErinvanderVeen** [comment]
Thank you for reporting this! I'll take a look as soon as I can find the time.

**Comment by yannham** [comment]
I haven't fiddled with tree-sitter myself, but don't we just feed it with a grammar description in JSON ? That's quite sad if an incorrect definition leads to a segfault :confused:

**Comment by yannham** [comment]
Ah, your PR seems to answer the question: no, it seems there is a hand-written C scanner which was the culprit.
