### ISSUE TITLE
Grammar railroad diagram

### ISSUE THREAD

**Issue by mingodad** [nickel-lang/tree-sitter-nickel#24]
Using this page https://meimporta.eu/tree-sitter/json2ebnf.html we can get a navigable railroad diagram for tree-sitter grammars like this project.

See also https://github.com/tree-sitter/tree-sitter/issues/2268 .

Cheers !

**Comment by ErinvanderVeen** [comment]
Thank you for your comment and making us aware of such a tool. However, we do not currently have any need for it.

As per https://github.com/tree-sitter/tree-sitter/discussions/2269, I'm closing this issue.
