### ISSUE TITLE
Nickel string parsing is not greedy enough

### ISSUE THREAD

**Issue by YorikSar** [nickel-lang/tree-sitter-nickel#26]
`m%` strings are parsed by Nickel greedier than by the tree-sitter. For example, string `m%""%{x}""%` is formatted by the Topiary to `m%""% { x } "" %` so it assumes that first `"%` closes the string, while Nickel itself consumes everything up to last `"%`.
This causes problems when embedding shell code in Nickel strings, for example:
```
nix-s%"
export PATH="%{inputs.coreutils}/bin:$PATH"
"%
```
this is parsed by Nickel just fine, but Topiary complains:

```
Parsing error between line 2, column 38 and line 2, column 39
```
because first `"%` closed the string, and the dollar sign is not allowed in this place outside the string.

**Comment by matthew-healy** [comment]
In particular, the relevant rules in the Nickel lexer are [here](https://github.com/tweag/nickel/blob/master/src/parser/lexer.rs#L425-L439). The broad intention is that `"(%+)` is only lexed as the ending token for the string if it's not immediately followed by the beginning of an interpolation (i.e. a `{` character).

I'm not familiar with how tree-sitter grammars are defined, so I'm not sure how complicated this would be to fix. @vkleen - do you have any idea?

**Comment by vkleen** [comment]
The problem with tree-sitter-grammar is that we don't have an easy way to do the same modal lexing that Nickel is doing. So the entire string handling is a bit of a hack. I'm looking into this but I'm not yet sure how we could fix it.
